version: '2.1'

services:

  telegram-bot:
    image: com.kgribov/telegram-bot
    environment:
      - TZ="UTC-8"
      - BOT_API_KEY
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    volumes:
      - bot-logs:/app/logs
    networks:
      - bot-network
    depends_on:
      database:
        condition: service_healthy
      logstash:
        condition: service_started

  database:
    image: postgres
    environment:
      - TZ="UTC-8"
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - bot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  logstash:
    build:
      context: logstash/
    volumes:
      - bot-logs:/usr/share/logstash/bot_logs:ro
    ports:
      - "5000:5000"
    environment:
      TZ: "UTC-8"
      LS_JAVA_OPTS: "-Xmx128m -Xms128m"
    networks:
      - monitoring
    depends_on:
      - graphite

  graphite:
    build:
      context: graphite/
    ports:
      - "8080:80"
    environment:
      TZ: "UTC-8"
    networks:
      - monitoring

  grafana:
    build:
      context: grafana/
    ports:
      - "9999:3000"
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      TZ: "UTC-8"
    networks:
      - monitoring
    depends_on:
      - logstash

volumes:
  bot-logs:
  database-data:

networks:
  bot-network:
    driver: bridge
  monitoring:
    driver: bridge
