version: '2'

services:

  telegram_bot:
    image: com.kgribov/telegram-bot
    environment:
      - TZ="UTC-8"
      - BOT_API_KEY
    volumes:
      - ./logs/:/app/logs

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logs/:/usr/share/logstash/bot_logs:ro
    ports:
      - "5000:5000"
    environment:
      TZ: "UTC-8"
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - monitoring
    depends_on:
      - graphite

  graphite:
    image: hopsoft/graphite-statsd
    volumes:
      - ./graphite/conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
    ports:
      - "8080:80"
    environment:
      TZ: "UTC-8"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    ports:
      - "9999:3000"
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      TZ: "UTC-8"
    networks:
      - monitoring
    depends_on:
      - logstash


networks:
  monitoring:
    driver: bridge
