{
 "title": "Telegram bot dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Income messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(summarize(telegram.bot.*.metric_text_messages.sum, '20s', 'sum', 'false'), 'Text messages')"
    },
    {
     "target": "alias(summarize(telegram.bot.*.metric_command_messages.sum, '20s', 'sum', 'false'), 'Commands messages')"
    },
    {
     "target": "alias(summarize(telegram.bot.*.metric_keyboard_replies.sum, '20s', 'sum', 'false'), 'Keyboard replies')"
    }
   ]
  },
  {
   "title": "24h messages count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "summarize(telegram.bot.*.metric_text_messages.sum, '1d', 'sum', false)"
    }
   ]
  },
  {
   "title": "Messages per hour",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "summarize(telegram.bot.*.metric_text_messages.sum, '1h', 'sum', 'false')"
    }
   ]
  },
  {
   "title": "Active dialogs",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(summarize(telegram.bot.*.metric_dialogs.max, '20s', 'max', false), 'Active dialogs')"
    }
   ]
  },
  {
   "title": "State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(summarize(telegram.bot.*.metric_dialogs.max, '20s', 'max', 'false'), 'Active dialogs')"
    },
    {
     "target": "alias(summarize(telegram.bot.*.metric_scheduled_commands.max, '20s', 'max'), 'Scheduled commands')"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(derivative(keepLastValue(telegram.bot.*.fail_to_load_updates.count, 100)), 'Unable to load by offset')"
    },
    {
     "target": "alias(derivative(keepLastValue(telegram.bot.*.unable_to_send.count, 100)), 'Unable to send replies')"
    },
    {
     "target": "alias(derivative(keepLastValue(telegram.bot.*.fail_to_request.count, 100)), 'Failed requests')"
    }
   ]
  }
 ]
}